### ISSUE TITLE
yarn build errror

### ISSUE THREAD

**Issue by planet4** [atosorigin/grafana-weathermap#2]
I would really like to try this. However when running yarn build I do get the error below. Would it be possible to add some screenshots how the weathermaps may look like?

at rejected (/var/lib/grafana/plugins/grafana-weathermap/node_modules/tslib/tslib.js:108:69)
✖ f.getRuleSeverity is not a function
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
.

**Comment by hellosct1** [comment]
Hi,

We have deployed a new version which is an intermediate version.
A documentation is available with details (draft version)
Other versions are planned very soon.

Thanks
