### ISSUE TITLE
yarn watch never completes?

### ISSUE THREAD

**Issue by MrDibbley** [atosorigin/grafana-weathermap#3]
running yarn watch ( redhat 7 ) just hangs after:

` Compiled successfully!

  Hash: 4884309847d5af6c9bb0
  Version: webpack 4.35.0
  Time: 16776ms
  Built at: 02/13/2020 14:38:40
                  Asset       Size  Chunks                    Chunk Names
                LICENSE   11.1 KiB          [emitted]
   Localization/en.json   2.92 KiB          [emitted]
   Localization/fr.json   3.09 KiB          [emitted]
              README.md   1.18 KiB          [emitted]
         img/NewTux.svg   20.6 KiB          [emitted]
  img/fleche-droite.svg  793 bytes          [emitted]
  img/fleche-gauche.svg   1.19 KiB          [emitted]
       img/grafana.jpeg   16.8 KiB          [emitted]
           img/logo.svg   34.3 KiB          [emitted]
             index.html  183 bytes          [emitted]
              module.js    494 KiB  module  [emitted]  [big]  module
          module.js.map    616 KiB  module  [emitted]         module
            plugin.json  685 bytes          [emitted]
  Entrypoint module [big] = module.js module.js.map
  [../node_modules/tslib/tslib.es6.js] 9.21 KiB {module} [built]
  [./Localization/en.json] 2.92 KiB {module} [built]
  [./Models/CoordinateSpaceClass.tsx] 1.5 KiB {module} [built]
  [./Models/OrientedLinkClass.tsx] 6.71 KiB {module} [built]
  [./Models/SettingMetricClass.tsx] 1.95 KiB {module} [built]
  [./Models/TextObjectClass.tsx] 1.29 KiB {module} [built]
  [./SimpleEditor.tsx] 11 KiB {module} [built]
  [./SimplePanel.tsx] 17.2 KiB {module} [built]
  [./components/CoordinateSpace/manageCoordinateSpace.tsx] 7.08 KiB {module} [built]
  [./components/Draw/drawArrow.tsx] 6.8 KiB {module} [built]
  [./components/Draw/drawCircleCross.tsx] 8.89 KiB {module} [built]
  [./components/Draw/drawLinkWithCoordinates.tsx] 9.21 KiB {module} [built]
  [./module.ts] 264 bytes {module} [built]
  [./types.ts] 2.29 KiB {module} [built]
  [@grafana/data] external "@grafana/data" 42 bytes {module} [built]
      + 65 hidden modules
  Child html-webpack-plugin for "index.html":
           Asset     Size  Chunks  Chunk Names
      index.html  534 KiB       0
      Entrypoint undefined = index.html
      [../node_modules/html-webpack-plugin/lib/loader.js!../node_modules/html-webpack-plugin/default_index.ejs] 376 bytes {0} [built]
      [../node_modules/lodash/lodash.js] 528 KiB {0} [built]
      [../node_modules/webpack/buildin/global.js] 472 bytes {0} [built]
      [../node_modules/webpack/buildin/module.js] 497 bytes {0} [built]
`

**Comment by sbelondr** [comment]
Hi,
`yarn watch` is used to build when project file change. When terminal display `Compiled successfully!` the plugin is launch and you can restart Grafana. But the plugin is still in development.

**Comment by MrDibbley** [comment]
no problems, so left yarn watch running and restarted grafana, created a new panel and selected weathermap and this error is displayed:

`An unexpected error happened
Details
Invariant Violation: Minified React error #130; visit https://reactjs.org/docs/error-decoder.html?invariant=130&args[]=undefined&args[]= for the full message or use the non-minified dev environment for full errors and additional helpful warnings. 

    in div
    in SimpleEditor
    in div
    in r
    in c
    in div
    in div
    in div
    in e
    in t
    in div
    in t
    in t
    in d
    in Unknown
    in div
    in div
    in t
    in d
    in div
    in t
    in div
    in e
    in DraggableCore
    in e
    in div
    in ReactGridLayout
    in Unknown
    in SizeMeReferenceWrapper
    in SizeMeRenderer(Component)
    in SizeMe(Component)
    in e
    in div
    in div
    in div
    in e
    in t
    in div
    in div
    in e
    in d
    in n
    in Unknown
    in p
    in Unknown
    in Unknown
    in t
    in t
    in d`

Thanks for your time

**Comment by sbelondr** [comment]
What version do you use for Grafana?

**Comment by MrDibbley** [comment]
6.5.3

Thanks

**Comment by sbelondr** [comment]
You can see in Readme. You have to use Grafana 6.7. A stable version will be released at the end of the mounth, I invite you to wait a little bit to test this one

**Comment by MrDibbley** [comment]
Thanks 6.6 shows the grid with no errors, happy to close this issues off
